# Generated by Django 4.1.3 on 2022-11-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='voice_record',
            field=models.FileField(upload_to='records/'),
        ),
    ]
